//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_cs
    {
        public string exception { get; set; }
        public string material { get; set; }
        public string plant { get; set; }
        public string storage_location { get; set; }
        public string material_description { get; set; }
        public string base_unit_of_measure { get; set; }
        public string batch { get; set; }
        public int unrestricted { get; set; }
        public int in_quality { get; set; }
        public int blocked { get; set; }
        public int total_stock { get; set; }
        public string market { get; set; }
        public int week { get; set; }
        public string year { get; set; }
        public string warehouse { get; set; }
        public int id { get; set; }
    
        public virtual storage storage { get; set; }
    }
}
